version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: mapos_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    restart: always
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    container_name: mapos_php
    # Constr√≥i a imagem localmente usando o Dockerfile na pasta etc/php
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "../:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    environment:
      - APP_BASEURL=${APP_BASEURL}

  whatsapp:
    image: node:20-slim
    container_name: mapos_whatsapp
    working_dir: /var/www/html/api/whatsapp
    environment:
      - PORT=3000
    volumes:
      - "../:/var/www/html"
    command: sh -c "npm install && node server.js"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: mapos_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mapos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mapos
      - MYSQL_PASSWORD=mapos
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mapos_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mapos_mysql
      - PMA_USER=mapos
      - PMA_PASSWORD=mapos
    restart: always
    depends_on:
      - mysql

volumes:
  mysql_data:
